name: Minimum mirai compatibility
on:
  push:
    branches: [main, master]
  pull_request:
permissions: read-all
jobs:
  minimum-mirai:
    runs-on: ubuntu-latest
    env:
      NOT_CRAN: true
      SHINYOAUTH_BROWSER_TESTS: false
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      - uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          extra-packages: |
            any::remotes
            any::pkgload
          needs: check
      - name: Install and test actual minimum mirai release
        shell: Rscript {0}
        run: |
          remotes::install_version("nanonext", version = "1.7.1", upgrade = "never")
          remotes::install_version("mirai", version = "2.5.1", upgrade = "never")
          stopifnot(packageVersion("mirai") == "2.5.1")
          pkgload::load_all()
          testthat::test_local(filter = "mirai-utils|module-server-async|helper-otel", stop_on_failure = TRUE)
